spring:
    application:
        name: sathish-data-consumer
    kafka:
        bootstrap-servers: localhost:7092
        consumer:
            auto-offset-reset: earliest
            group-id: test-sathish-data-consumer
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
