# Golden copy for the client to communicate with Configserver ver #3
# this property file setting will read app name "Accounts", profile "local" and use the retry logic
spring:
  application:
    name: "garmindatainitializer"
  cloud:
    config:
      username: ${configserverUsername}
      password: ${configserverPassword}
  config:
    name: garmindatainitializer
    username: ${configserverUsername}
    password: ${configserverPassword}
    uri: http://localhost:8888
    fail-fast: true
    import: "optional:configserver:http://40.124.92.101:8888/?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1000"
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
