server:
    port: 8065
spring:
    application:
        name: sathishstrava-data-producer
    kafka:
        bootstrap-servers: 192.168.5.68:9092
        topic:
            name: sathish-garmin
        template:
            default-topic: sathish-garmin

        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            properties:
                acks: all
                retries: 0
                batch-size: 16384
                linger-ms: 1
                buffer-memory: 33554432
        admin:
            properties:
                bootstrap.servers: 192.168.5.68:9092

    cloud:
        config:
            username: ${configserverUsername}
            password: ${configserverPassword}
    config:
        fail-fast: true
        import: "optional:configserver:http://localhost:8888/?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100"
    threads:
        virtual:
            enabled: on
