# Golden copy for the client to communicate with Configserver ver #3
# this property file setting will read app name "Accounts", profile "local" and use the retry logic
spring:
    application:
        name: "trackgarmin"
    cloud:
      config:
          username: ${configserverUsername}
          password: ${configserverPassword}
    config:
        username: ${configserverUsername}
        password: ${configserverPassword}
        uri: ${configuri}
        fail-fast: true
        import: "optional:configserver:http://${configuri}/?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1000"
    threads:
        virtual:
            enabled: on
server:
    port: 9042
    servlet:
        context-path: /trackgarmin

