spring:
    application:
        name: sathishruns-common
    cloud:
        config:
            username: ${configserverUsername}
            password: ${configserverPassword}
    config:
        fail-fast: true
        import: "optional:configserver:http://localhost:8888/?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1000"
sathishruns-retry-config:
    initial-interval-ms: 1000
    max-interval-ms: 10000
    multiplier: 2.0
    maxAttempts: 3
    sleep-time-ms: 2000

sathishruns-kafka-config:
    bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
    schema-registry-url-key: schema.registry.url
    schema-registry-url: http://localhost:8081
    topic-name: twitter-topic
    topic-names-to-create:
        - twitter-topic
    num-of-partitions: 3
    replication-factor: 3

kafka-producer-config:
    key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
    value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
    compression-type: snappy
    acsk: all
    batch-size: 16384
    batch-size-boost-factor: 100
    linger-ms: 5
    request-timeout-ms: 60000
    retry-count: 5
