server:
    port: 7070
spring:
    application:
        name: sathishruns-common
    cloud:
        config:
            username: ${configserverUsername}
            password: ${configserverPassword}
    config:
        fail-fast: true
        import: "optional:configserver:http://${configserver}/?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1000"
