spring:
  application:
    name: event-service
  cloud:
    config:
      username: ${configserverUsername}
      password: ${configserverPassword}
  config:
    name: event-service
    username: ${configserverUsername}
    password: ${configserverPassword}
    uri: ${configuri}
    fail-fast: true
    import: "optional:configserver:http://${configuri}/?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1000"
######## App Configuration #########
app:
  cors:
    path-pattern: /api/**
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"

################ Actuator #####################
management:
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info,logfile,loggers
  endpoint:
    health:
      show-details: when_authorized

################ Database #####################
server:
  port: 8082
